@echo off
echo Creating a new orphan branch...
git checkout --orphan latest_branch
echo Adding clean files...
git add -A
echo Committing clean state...
git commit -am "Initial commit (removed large files)"
echo Deleting old branch...
git branch -D main
echo Renaming branch...
git branch -m main
echo Forcing push to GitHub...
git push -f --set-upstream origin main
echo Done.
