@echo off
echo Removing bloated .git directory...
rmdir /s /q .git
echo Initializing fresh git repository...
git init
echo Configuring remote...
git remote add origin https://Shakthi-root@github.com/Shakthi-root/Crowd_Monitoring.git
echo Adding files...
git add .
echo Committing...
git commit -m "Initial commit"
echo Renaming branch...
git branch -m main
echo Pushing to GitHub...
git push -u origin main -f
echo Cleanup complete.
